### ISSUE TITLE
[BUG]: contract upload transaction stuck in the mempool

### ISSUE THREAD

**Issue by harpagon210** [koinos/koinos-mempool#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When uploading [this contract.wasm](https://github.com/koinos/koinos-mempool/files/7679298/contract.wasm.zip), the transaction gets stuck in the mempool with no errors showing as to why it cannot be included in a block.

When lowering the size of the wasm, I'm able to upload it so it might be related to the file size.

### Expected behavior

either reject the transaction with a proper error message or include the transaction in a block

### Steps to reproduce

1. open the Koinos CLI
2. open a wallet
3. connect to any RPC node (i.e.: http://api.koinos.io:8080)
4. upload [this contract.wasm](https://github.com/koinos/koinos-mempool/files/7679298/contract.wasm.zip) with `upload contract.wasm`

In the mempool service logs you should see something like `2021-12-08 21:15:39.989639 (mempool.Koinos) [mempool.cpp:243] <info>: Transaction added` , but you won't see `[mempool.cpp:257] <info>: Removing included transaction from mempool...`

### Environment

```markdown
- OS: all
```

**Comment by mvandeberg** [comment]
This is an old transaction. Logic for block construction and transaction inclusion has changed drastically since then and we have not experienced similar problems on Testnet 4.
