### ISSUE TITLE
[BUG]: Boost:filesystem::filesystem_error at node start

### ISSUE THREAD

**Issue by motoeng** [koinos/koinos-mempool#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running node on a VPS (vpsdime), the mempool microservice throws a fatal error. Similar error for block_producer

mempool_1              | 2022-10-03 21:19:13.789565 (mempool.Koinos) [main.cpp:331] <fatal>: An unexpected error has occurred: boost::filesystem::create_directories: Function not implemented: "/koinos/mempool/logs"
mempool_1              | terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
mempool_1              |   what():  boost::filesystem::create_directories: Function not implemented: "/koinos/mempool/logs"
koinos_mempool_1 exited with code 139

### Environment

```markdown
- OS:
Ubuntu 20.04.5 LTS
```

**Comment by mvandeberg** [comment]
Is this still an issue? Since the bug report we have bumped the boost version in mempool?
